## CLEANING DATAFRAME ##

In [2]:
# importing required packages
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np
import re

In [3]:
# reading the extracted dataframe 

car_details = pd.read_csv('car_details.csv', dtype={13: 'str'})

car_details.iloc[:, 30:40]

,Engine Type,Displacement,Max Power,Max Torque,No of Cylinder,Values per Cylinder,Fuel Suppy System,Turbo Charger,Length,Width
0,Smartstream G1.0 T - GDi,998.0,118.36bhp@6000rpm,172nm@1500-4000rpm,3.0,4.0,GDi,Yes,3995mm,1790
1,In-Line Engine,1196.0,73bhp@6000rpm,101Nm@3000rpm,4.0,4.0,MPFi,No,3675mm,1475mm
2,HRA0 1.0 TURBO PETROL,999.0,98.63bhp@5000rpm,160Nm@2800-3600rpm,3.0,4.0,MPFi,Yes,3994mm,1758
3,IRDE2 Engine,1086.0,68.05bhp@5500rpm,99.04Nm@4500rpm,4.0,3.0,MPFI,No,3585mm,1595mm
4,i-VTEC Petrol Engine,1199.0,88.7bhp@6000rpm,110Nm@4800rpm,4.0,4.0,PGM - Fi,No,3955mm,1694mm
...,...,...,...,...,...,...,...,...,...,...
8364,K10C,998.0,65.71bhp@5500rpm,89Nm@3500rpm,3.0,4.0,NaN,NaN,3695mm,1655
8365,F8D Petrol Engine,796.0,47.3bhp@6000rpm,69Nm@3500rpm,3.0,4.0,MPFi,No,3395mm,1490mm
8366,Blue Efficiency Engine,1796.0,186bhp@5600rpm,285Nm@2400-4000rpm,4.0,4.0,Mpfi,No,4591mm,1770mm
8367,K Series Petrol Engine,1197.0,85.80bhp@6000rpm,114Nm@4000rpm,4.0,4.0,MPFI,No,3775mm,1680mm
8368,dCi THP Diesel Engine,1461.0,108.45bhp@4000rpm,245Nm@1750rpm,4.0,4.0,CRDi,Yes,4315mm,1822mm

In [4]:
# changing the datatype of the columns 

#1. ignition type 
car_details['ignition_type'] = car_details['ignition_type'].astype(int)

#2. kilometers_driven
car_details['kilometers_driven'] = car_details['kilometers_driven'].str.replace(",", "")
car_details['kilometers_driven'] = car_details['kilometers_driven'].astype(int)

#3. ownerNo
car_details['ownerNo'] = car_details['ownerNo'].astype(int)

#4. modelYear
car_details['modelYear'] = car_details['modelYear'].astype(int)

#5. centralVariantId
car_details['centralVariantId'] = car_details['centralVariantId'].astype(int)

#6. price
def get_price(row):
    try:
        try:
            pattern = r'\d+\.\d+'#creatign a pattern to extract price 
            result = re.search(pattern, str(row))# searching for pattern
            return float(result.group()) #returning the result 
        except AttributeError:
            pattern = r'\d+'# if the above pattern didn't found searching for this pattern
            result =re.search(pattern, str(row))
            return float(result.group())
        return 0
    except Exception as e:
        return 0
        
car_details['price'] = car_details['price'].apply(get_price)

#7.seats 
car_details['Seats'] = car_details['Seats'].apply(get_price)
car_details['Seats'] = car_details['Seats'].replace(0, None)

#8. Kmsdriven 
def getkms(row):
    try:
        pattern = r'\d+'
        result = re.search(pattern, str(row))
        return result.group()
    except Exception as e:
        return 0
car_details['Kms Driven'] = car_details['Kms Driven'].str.replace(",", "")
car_details['Kms Driven'] = car_details['Kms Driven'].apply(getkms)
car_details['Kms Driven'] = car_details['Kms Driven'].replace(0, None)

#9.Displacement
car_details['Displacement'] = car_details['Displacement'].fillna(0)
car_details['Displacement'] = car_details['Displacement'].replace(0, None)

#10.No of Cylinder
car_details['No of Cylinder'] = car_details['No of Cylinder'].fillna(0)
car_details['No of Cylinder'] = car_details['No of Cylinder'].replace(0, None)

#11.Gear Box
car_details['Gear Box'] = car_details['Gear Box'].fillna(0)
car_details['Gear Box'] = car_details['Gear Box'].str.replace(",", "")
car_details['Gear Box'] = car_details['Gear Box'].apply(getkms)
car_details['Gear Box'] = car_details['Gear Box'].replace(0, None)

#12.Front Tread 
car_details['Front Tread'] = car_details['Front Tread'].fillna(0)
car_details['Front Tread'] = car_details['Front Tread'].str.replace(",", "")
car_details['Front Tread'] = car_details['Front Tread'].apply(getkms)
car_details['Front Tread'] = car_details['Front Tread'].replace(0, None)

#13. Rear Tread
car_details['Rear Tread'] = car_details['Rear Tread'].fillna(0)
car_details['Rear Tread'] = car_details['Rear Tread'].str.replace(",", "")
car_details['Rear Tread'] = car_details['Rear Tread'].apply(getkms)
car_details['Rear Tread'] = car_details['Rear Tread'].replace(0, None)

#14.Top Speed
car_details['Top Speed'] = car_details['Top Speed'].fillna(0)
car_details['Top Speed'] = car_details['Top Speed'].apply(get_price)
car_details['Top Speed'] = car_details['Top Speed'].replace(0, None)

#15. Registration Year
car_details['Registration Year'] = car_details['Registration Year'].fillna(0)
car_details['Registration Year'] = car_details['Registration Year'].apply(getkms)

#16. length
car_details['Length'] = car_details['Length'].fillna(0)
car_details['Length'] = car_details['Length'].apply(get_price)
car_details['Length'] = car_details['Length'].replace(0, None)

#17. Width
car_details['Width'] = car_details['Width'].fillna(0)
car_details['Width'] = car_details['Width'].apply(get_price)
car_details['Width'] = car_details['Width'].replace(0, None)

#18. Height
car_details['Height'] = car_details['Height'].fillna(0)
car_details['Height'] = car_details['Height'].apply(get_price)
car_details['Height'] = car_details['Height'].replace(0, None)

#19. Wheel Base
car_details['Wheel Base'] = car_details['Wheel Base'].fillna(0)
car_details['Wheel Base'] = car_details['Wheel Base'].apply(get_price)
car_details['Wheel Base'] = car_details['Wheel Base'].replace(0, None)

#20. Kerb Weight
car_details['Kerb Weight'] = car_details['Kerb Weight'].fillna(0)
car_details['Kerb Weight'] = car_details['Kerb Weight'].apply(get_price)
car_details['Kerb Weight'] = car_details['Kerb Weight'].replace(0, None)

#20. No Door Numbers
car_details['No Door Numbers'] = car_details['No Door Numbers'].fillna(0)
car_details['No Door Numbers'] = car_details['No Door Numbers'].apply(get_price)
car_details['No Door Numbers'] = car_details['No Door Numbers'].replace(0, None)

print('data type changed')

data type changed

In [5]:
# cleaning datas in Steering Type
def steering_type(row):
    row = str(row)
    if (row.lower() == 'electric' or row.lower() == 'electrical' or row.lower() == "electronic" or row.lower() == 'epas'):
        return 'electric'
    elif (row.lower() == 'manual'):
        return 'manual'
    elif (row.lower() == 'power'):
        return 'power'
    else:
        return 'hydraulic'

car_details['Steering Type'] = car_details['Steering Type'].apply(steering_type)

In [6]:
# cleaning insurance validity
def clean_insurance(row):
    if (row.lower() == 'petrol' or row.lower() == 'diesel' or row.lower() == 'electric'):
        return None
    elif row == 'Third Party insurance':
        return 'Third Party'
    elif (row == 'Not Available' or str(row) == '1' or str(row) == '2'):
        return None
    else: 
        return row

car_details['Insurance Validity'] = car_details['Insurance Validity'].apply(clean_insurance)

In [7]:
car_details.iloc[:, 60:70]

     Top Speed   Acceleration BoreX Stroke Ground Clearance Unladen
0         None            NaN          NaN                      NaN
1        145.0   15.7 Seconds          NaN                      NaN
2         None           11.7  72.2 x 81.3                      NaN
3        165.0   14.3 Seconds          NaN                      NaN
4        172.0   13.7 Seconds          NaN                      NaN
...        ...            ...          ...                      ...
8364      None            NaN          NaN                      NaN
8365     140.0     19 Seconds          NaN                      NaN
8366     230.0    8.8 Seconds          NaN                      NaN
8367     156.0     15 Seconds          NaN                      NaN
8368     168.0  14.20 Seconds          NaN                      NaN

[8369 rows x 4 columns]

## cleaning the null values ##

In [9]:
#droping the columns with null values in body_type
car_details.dropna(subset=['body_type'], inplace=True)

In [10]:
# eleminating the null value in kms Driven
mode_ = car_details['Kms Driven'].dropna().mode()[0]
car_details['Kms Driven'] = car_details['Kms Driven'].fillna(mode_)

In [11]:
# eleminating the null values in Transmission
mode_ = car_details['transmission'].dropna().mode()[0]
car_details['transmission'] = car_details['transmission'].fillna(mode_)

In [12]:
# eleminating the null values in color
mode_ = car_details['Color'].dropna().mode()[0]
car_details['Color'] = car_details['Color'].fillna(mode_)

In [13]:
#eleminating the null values in Displacement
mean_ = car_details['Displacement'].dropna().astype(int).median()
car_details['Displacement'] = car_details['Displacement'].astype(float).fillna(mean_)

In [14]:
# eliminating null values in No of Cylinder
mode_ = car_details['No of Cylinder'].dropna().mode()[0]
car_details['No of Cylinder'] = car_details['No of Cylinder'].astype(float).fillna(mode_)

In [15]:
# eleminating null values in gear box
mode_ = car_details['Gear Box'].dropna().mode()[0]
car_details['Gear Box'] = car_details['Gear Box'].astype(float).fillna(mode_)

In [16]:
# eleminating null values in steering type
mode_ = car_details['Steering Type'].dropna().mode()[0]
car_details['Steering Type'] = car_details['Steering Type'].fillna(mode_)

In [17]:
# eleminating null values Front Brake Type
mode_ = car_details['Front Brake Type'].dropna().mode()[0]
car_details['Front Brake Type'] = car_details['Front Brake Type'].fillna(mode_)

In [18]:
# eleminating null values Rear Brake Type
mode_ = car_details['Rear Brake Type'].dropna().mode()[0]
car_details['Rear Brake Type'] = car_details['Rear Brake Type'].fillna(mode_)

In [19]:
# eleminating null values from no of doors
mode_ = car_details['No Door Numbers'].dropna().mode()[0]
car_details['No Door Numbers'] = car_details['No Door Numbers'].astype(float).fillna(mode_)

In [20]:
# eleminating null values in Insurance validity
mode_ = car_details['Insurance Validity'].dropna().mode()[0]
car_details['Insurance Validity'] = car_details['Insurance Validity'].fillna(mode_)

In [21]:
# eleminating null values in Seating Capacity
mode_ = car_details['Seating Capacity'].dropna().mode()[0]
car_details['Seating Capacity'] = car_details['Seating Capacity'].fillna(mode_)

In [22]:
# eleminating null values in Seating Capacity
mode_ = car_details['Seats'].dropna().mode()[0]
car_details['Seats'] = car_details['Seats'].fillna(mode_)
car_details['Seats']= car_details['Seats'].astype(int)

In [23]:
# eleminating null values in length
car_details['Length'] = car_details['Length'].replace("0", None)
car_details['Length'] = car_details['Length'].astype(float)
mean_ = car_details['Length'].dropna().mode()[0]
car_details['Length'] = car_details['Length'].fillna(mean_)

In [24]:
# eleminating null values in width
car_details['Width'] = car_details['Width'].replace("0", None)
car_details['Width'] = car_details['Width'].astype(float)
mean_ = car_details['Width'].dropna().mode()[0]
car_details['Width'] = car_details['Width'].fillna(mean_)

In [25]:
# eleminating null values in height
car_details['Height'] = car_details['Height'].replace("0", None)
car_details['Height'] = car_details['Height'].astype(float)
mean_ = car_details['Height'].dropna().mode()[0]
car_details['Height'] = car_details['Height'].fillna(mean_)

In [26]:
# eleminating null values in wheel base
car_details['Wheel Base'] = car_details['Wheel Base'].replace("0", None)
car_details['Wheel Base'] = car_details['Wheel Base'].astype(float)
mean_ = car_details['Wheel Base'].dropna().mode()[0]
car_details['Wheel Base'] = car_details['Wheel Base'].fillna(mean_)

In [27]:
# eleminating null values in height
car_details['Height'] = car_details['Height'].replace("0", None)
car_details['Height'] = car_details['Height'].astype(float)
mean_ = car_details['Height'].dropna().mode()[0]
car_details['Height'] = car_details['Height'].fillna(mean_)

In [28]:
# eleminating null values in Kerb WeightNo Door Numbers
car_details['Kerb Weight'] = car_details['Kerb Weight'].replace("0", None)
car_details['Kerb Weight'] = car_details['Kerb Weight'].astype(float)
mean_ = car_details['Kerb Weight'].dropna().mode()[0]
car_details['Kerb Weight'] = car_details['Kerb Weight'].fillna(mean_)

In [29]:
# eleminating null values in No Door Numbers
mean_ = car_details['No Door Numbers'].dropna().mode()[0]
car_details['No Door Numbers'] = car_details['No Door Numbers'].fillna(mean_)

In [30]:
# eleminating null values in Top Speed
car_details['Top Speed'] = car_details['Top Speed'].replace("0", None)
car_details['Top Speed'] = car_details['Top Speed'].astype(float)
mean_ = car_details['Top Speed'].dropna().mode()[0]
car_details['Top Speed'] = car_details['Top Speed'].fillna(mean_)

In [31]:
# removing the misarranged values
def name(row):
    if float(row) > 7.0:
        return None
    else:
        return float(row)

car_details['Seats'] = car_details['Seats'].apply(name)
car_details.dropna(subset='Seats', axis=0, inplace=True)

In [32]:
# removing the outlier in no of cylinder

def cyli(row):
    if float(row) == 23:
        return None
    else:
        return int(row)

car_details['No of Cylinder'] = car_details['No of Cylinder'].apply(cyli)

car_details.dropna(subset='No of Cylinder', axis=0, inplace=True)

## Droping the unwanted columns ##

In [34]:
car_details.drop(['Fuel Type', 'Color','Registration Year', 'Seating Capacity', 'centralVariantId', 'model', 'kilometers_driven','Front Brake Type', 'Rear Brake Type', 'RTO', 'Transmission', 'ignition_type', 'owner', 'variantName', 'priceActual', 'Max Power', 'Max Torque', 'Turbo Charger', 'priceSaving', 'priceFixedText', 'trendingText', 'index_number', 'RTO', 'Ownership', 'Engine Displacement', 'Year of Manufacture', 'Engine Type', 'Values per Cylinder', 'Fuel Suppy System', 'Drive Type', 'Tyre Type', 'Alloy Wheel Size', 'Cargo Volumn', 'Value Configuration', 'Compression Ratio', 'Super Charger', 'Front Tread', 'Rear Tread', 'Gross Weight', 'Turning Radius', 'Acceleration', 'BoreX Stroke', 'Ground Clearance Unladen'], axis=1, inplace=True)

print("Some columns dropped")

Some columns dropped

In [35]:
# changing the datatypes of the cloumns
#car_details['Registration Year'] = car_details['Registration Year'].astype(int)

# Kms Driven 
car_details['Kms Driven'] = car_details['Kms Driven'].astype(int)

# Gear box 
car_details['Gear Box'] = car_details['Gear Box'].astype(int)

In [36]:
# Reseting index

car_details.reset_index(inplace=True)
car_details.drop('index', axis=1, inplace=True)

## ENCODING CATEGORICAL VARIABLES ##

In [38]:
# Using one hot encoder for body_type 

ohe = OneHotEncoder(sparse_output=False)

label = LabelEncoder()
value = ohe.fit_transform(car_details[['body_type']])

features = ohe.get_feature_names_out(['body_type'])

body_type = pd.DataFrame(value, columns=features)

col = [car_details.columns] + [body_type.columns]

car_details = pd.concat([car_details, body_type], axis=1)

car_details.drop('body_type', axis=1, inplace=True)

In [39]:
# Using lable encoding for location

label = LabelEncoder()

car_details['Location'] = label.fit_transform(car_details['location'])

car_details.drop('location', axis=1, inplace=True)

In [40]:
# using label encoder for transmission

car_details['Transmission'] = label.fit_transform(car_details['transmission'])

car_details.drop('transmission', axis=1, inplace=True)

In [41]:
# using one-hot encoder in Steering type

value = ohe.fit_transform(car_details[['Steering Type']])

features = ohe.get_feature_names_out(['Steering Type'])

steering_type = pd.DataFrame(value, columns=features)

col = [car_details.columns] + [steering_type.columns]

car_details = pd.concat([car_details, steering_type], axis=1)

car_details.drop('Steering Type', axis=1, inplace=True)

In [42]:
# using one-hot encoder in fuel_type

value = ohe.fit_transform(car_details[['fuel_type']])

features = ohe.get_feature_names_out(['fuel_type'])

steering_type = pd.DataFrame(value, columns=features)

col = [car_details.columns] + [steering_type.columns]

car_details = pd.concat([car_details, steering_type], axis=1)

car_details.drop('fuel_type', axis=1, inplace=True)

In [43]:
# using one-hot encoder for oem 

value = ohe.fit_transform(car_details[['oem']])

features = ohe.get_feature_names_out(['oem'])

manufacturer = pd.DataFrame(value, columns=features)

col = [car_details.columns] + [manufacturer.columns]

car_details = pd.concat([car_details, manufacturer], axis=1)

car_details.drop('oem', axis=1, inplace=True)

In [44]:
# using one-hot encoder for insurance validity

value = ohe.fit_transform(car_details[['Insurance Validity']])

features = ohe.get_feature_names_out(['Insurance Validity'])

insurance = pd.DataFrame(value, columns=features)

col = [car_details.columns] + [insurance.columns]

car_details = pd.concat([car_details, insurance], axis=1)

car_details.drop('Insurance Validity', axis=1, inplace=True)

In [45]:
#storing the result as csv file

car_details.to_csv('cleaned_details.csv')

## OUTCOMES ##

Outcomes from Cleaning the data

1. droping the null values
    - the rows that has null values in body_type is completely droped 

2. Extracting the data 
    - regular expression is used to extract some values
    - eg => price, kilometes

3. Changing the datatypes 
    - the "nan" values are changed to 0
    - the datatype of the column is changed

4. clearing the null values 
    - the null values of continuous variables are cleared by using mean or median
    - the null values of categorical variables are cleared by using mode values  

5. Droping the unwanted values
    - the values that make no sense and has more null values are dropped

6. Encoding categorical values
    - ordinal datas are converted to numerical using label-encoding
    - nominal datas are converted to numerical using one-hot enoding

7. Normalizing the columns
    - the columns that has large distance is normalized 
    - min-max scaling is used here on couple of columns

8. removing outliers (not done):
    - removing outliers is not done because it is completely damaging the dataset